# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "k+iYtaOBQeqc3ka7ubvwBU3CwIP7qhlNhDIyS+X7HM9rHj6X2AQtEXd1cSp7wISXY3NeK95+9AV+FLWcNTropNePqKyRCYZerzOPKgMghT6yQipw7KQvIGNm6mXS/fHwP/IwLeTX9VsDJ8YT3tf2NPUv2CVfL/gIo2PLIxNB/08THopA0bjGmeOtK/7CRRL7Y/xpo1U7Hz+rxsk+rSEjafre/WicISEuTY0wf3UFYTRaTOm9ioEsbE13N8yIxl5GA6BwCjNYKhbP4hXJ4wDxIOb9AyvfSGu01cxcbddnL05X/JV7gjcSvQObaOJIHA+OckvktW1OySI9ETEhmBcu9LTZ86Hx+o/9PzMIRN8bd/6PBRWAyoY1pF4yLKb0aiqUgZWlWG+gya07fgIpI5bS3fOxaPUmG1hO5RiECYlywkJyAYaewg5CFgpo48ei0+z0rDvyrF6zFd0Eyr+gmRZMfhbOGkbxF7kDOOuTs5DfdKOD2fBbyPJpuxlF8M8Gkbs9F6TySZePoSQ8uCgzkG6QmIobhRHXEAwgLL+34KOtycSk9Hdhh5ez5XqaBSmgkIk2k3f8HYGfZVWJIY3WvhSVVZr4WOSNNkVu3ZRJercvj9yGZN7aZIxHO/IpMf5VtgUqvzfwKv2mUgH8RV3wngUfyIgBt85eqJkstxD24SUYwX4="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  -  conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml